engines:
  rubocop:
    enabled: true
  golint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python
      - javascript
      - html
      - css
ratings:
  paths:
  - "**.py"
  - "**.html"
  - "**.css"
  - "**.js"
exclude_paths:
- "**/tests/**"
- "**/test_**.py"
